In [1]:
from envs.build_env import get_instance_env

In [2]:
env = get_instance_env('mario',1,1)

In [5]:
obs = env.reset()

In [8]:
env2 = env.unwrapped

In [10]:
obs2 = env2.reset()

In [11]:
obs2.shape

(240, 256, 3)

In [2]:
num=1
world=1
stage=1

In [3]:
r"D:\reinforce\mario\my_mario\ckpt\{}_get_flag_{}_{}.pth.tar".format(num,world,stage)

'D:\\reinforce\\mario\\my_mario\\ckpt\\1_get_flag_1_1.pth.tar'

In [3]:
a = (1,2,3)

SyntaxError: invalid syntax (394553381.py, line 1)

In [3]:
import torch 

In [4]:
a = torch.zeros(size=(1000,4,84,84),dtype=torch.float)

In [ ]:
a.unsqueeze(dim=0)

tensor([[[[[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           ...,
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.]],

          [[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           ...,
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.]],

          [[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           ...,
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.]],

          [[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           ...,
           [0., 0., 0.,  ..

In [8]:
import torch

In [11]:
a = torch.rand(size=(20,))

In [13]:
a.share_memory_()

tensor([0.6303, 0.4328, 0.2565, 0.6208, 0.5088, 0.1882, 0.8613, 0.5211, 0.1083,
        0.2713, 0.1287, 0.1506, 0.2793, 0.0326, 0.6263, 0.2653, 0.4565, 0.8845,
        0.9333, 0.0849])

In [14]:
a.is_shared()

True

In [15]:
a.data_ptr()

1683062784064

In [16]:
a.data.data_ptr()

1683062784064

In [4]:
a = 12

In [5]:
a -=a

In [7]:
a += a

In [8]:
a

0

In [1]:
import torch

In [3]:
x = torch.randn(size = (20,3))

In [6]:
x.mean(axis = 0)

tensor([ 0.1521,  0.2680, -0.0871])

In [2]:
a = torch.tensor(512)
a

tensor(512)

In [3]:
a.item()

512

In [21]:
if a > 5:
    print(a)

tensor(512)


In [14]:
a += 1

In [15]:
a

tensor(1)

In [16]:
a.is_shared()

False